package com.anvith.archmorph.pipeline;

/** Structured progress events exposed to the frontend. */
public enum ProgressEvent {
    UPLOAD_COMPLETE,
    EXTRACTION_COMPLETE,
    STRUCTURE_DETECTED,
    PARSING_STARTED,
    PARSING_COMPLETE,
    DEPENDENCY_ANALYSIS_COMPLETE,
    ARCHITECTURE_ANALYSIS_COMPLETE,
    MODULE_DISCOVERY_COMPLETE,
    PLAN_CREATED,
    TRANSFORMATION_STARTED,
    TRANSFORMATION_COMPLETE,
    VALIDATION_STARTED,
    VALIDATION_COMPLETE,
    REPORTS_GENERATED
}
